#!/usr/bin/env python3
"""Procedure Reduce 

Input: a bug-triggering .smt2 file (as produced by dedup.py --
named 'incorrect-...smt2' for a soundness bug or 'crash-...smt2' for a
crash)
Output: the same file, minimized in place by creduce

The interestingness test creduce drives is generated from this script and
reuses dedup.py's exact confirm_crash()/confirm_soundness() -- the same
crash-signature match and model-grounding cross-check dedup() itself uses
-- so a "reduction" can't wander into some other, unrelated bug, and
soundness reductions can't flip a solution-soundness bug into a
refutational one (or vice versa) partway through.
"""

import argparse
import shutil
import stat
import subprocess
import sys
import textwrap
from pathlib import Path

import dedup

ERR_USAGE = 2

INTERESTINGNESS_TEST = """\
#!/usr/bin/env python3
# Generated by reduce.py -- do not edit by hand, it's regenerated per run.
import sys
from pathlib import Path

sys.path.insert(0, {dedup_dir!r})
import dedup

SMTFILE = Path({smtfile!r})
TARGET_CMD = {target_cmd!r}
ORACLE_CMD = {oracle_cmd!r}
TARGET_MSG = {target_msg!r}

if {is_soundness!r}:
    msg = dedup.confirm_soundness(SMTFILE, SMTFILE.read_text(errors="ignore"), TARGET_CMD, ORACLE_CMD)
else:
    msg = dedup.confirm_crash(SMTFILE, TARGET_CMD)

sys.exit(0 if msg == TARGET_MSG else 1)
"""


def build_interestingness_test(smtfile_name, target_cmd, oracle_cmd, is_soundness, target_msg):
    return INTERESTINGNESS_TEST.format(
        dedup_dir=str(Path(__file__).resolve().parent),
        smtfile=smtfile_name,
        target_cmd=target_cmd,
        oracle_cmd=oracle_cmd or "",
        is_soundness=is_soundness,
        target_msg=target_msg,
    )


def reduce(smt2_path, target_cmd, oracle_cmd, out_dir, creduce_bin, jobs):
    kind = dedup.classify(smt2_path)
    if kind is None:
        print(
            f'error: "{smt2_path.name}" is not named like a dedup.py bug '
            'trigger (expected an "incorrect-...smt2" or "crash-...smt2" prefix)',
            flush=True,
        )
        exit(ERR_USAGE)
    is_soundness = kind == "soundness"

    if is_soundness and not oracle_cmd:
        print("error: --oracle-cmd is required to reduce a soundness bug", flush=True)
        exit(ERR_USAGE)

    if shutil.which(creduce_bin) is None:
        print(f'error: creduce not found (looked for "{creduce_bin}" on PATH)', flush=True)
        exit(ERR_USAGE)

    dedup.check_solver_installed(target_cmd)
    if oracle_cmd:
        dedup.check_solver_installed(oracle_cmd)

    text = smt2_path.read_text(errors="ignore")
    if is_soundness:
        target_msg = dedup.confirm_soundness(smt2_path, text, target_cmd, oracle_cmd)
    else:
        target_msg = dedup.confirm_crash(smt2_path, target_cmd)

    if target_msg is None:
        print(
            f'error: "{smt2_path.name}" does not currently reproduce a '
            f"{kind} bug against the given solver command(s) -- nothing to reduce",
            flush=True,
        )
        exit(ERR_USAGE)
    print(f"confirmed {kind} bug ({target_msg}) on {smt2_path.name}, reducing...", flush=True)

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    work_file = out_dir / smt2_path.name
    shutil.copy2(smt2_path, work_file)
    shutil.copy2(smt2_path, out_dir / (smt2_path.name + ".orig"))

    test_script = out_dir / "interestingness_test.py"
    test_script.write_text(
        build_interestingness_test(work_file.name, target_cmd, oracle_cmd, is_soundness, target_msg)
    )
    test_script.chmod(test_script.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    cmd = [creduce_bin]
    if jobs:
        cmd += ["--n", str(jobs)]
    cmd += [str(test_script.resolve()), work_file.name]

    result = subprocess.run(cmd, cwd=out_dir)
    if result.returncode != 0:
        print(f"error: creduce exited with code {result.returncode}", flush=True)
        exit(result.returncode)

    before = (out_dir / (smt2_path.name + ".orig")).stat().st_size
    after = work_file.stat().st_size
    print(f"reduced {smt2_path.name}: {before} -> {after} bytes, written to {work_file}", flush=True)
    return work_file


def parse_args(argv):
    parser = argparse.ArgumentParser(
        prog="reduce.py",
        description=textwrap.dedent(__doc__),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("smt2_file", help="the bug-triggering .smt2 file to minimize")
    parser.add_argument(
        "--target-cmd",
        required=True,
        help="target solver command line, e.g. 'z3 model_validate=true'",
    )
    parser.add_argument(
        "--oracle-cmd",
        help="oracle solver command line, required for soundness ('incorrect-...') triggers",
    )
    parser.add_argument(
        "--out-dir",
        default="reduced_out",
        help="directory creduce works in and writes the minimized file to (default: %(default)s)",
    )
    parser.add_argument("--creduce-bin", default="creduce", help="creduce executable (default: %(default)s)")
    parser.add_argument("--jobs", "-j", type=int, default=None, help="parallel creduce jobs (creduce --n)")
    return parser.parse_args(argv)


if __name__ == "__main__":
    args = parse_args(sys.argv[1:])
    reduce(
        Path(args.smt2_file),
        args.target_cmd,
        args.oracle_cmd,
        args.out_dir,
        args.creduce_bin,
        args.jobs,
    )
